featurevisor/featurevisor

docs/features.md, docs/segments.md, packages/core/src/linter.ts, packages/sdk/src/conditions.spec.ts, packages/sdk/src/conditions.ts, packages/sdk/src/segments.ts, packages/types/src/index.ts
=> feat: NOT operator

docs/features.md, docs/sdks.md, examples/example-1/features/bar.yml, examples/example-1/package.json, examples/example-1/tests/bar.spec.yml, packages/core/src/linter.ts, packages/core/src/tester.ts, packages/sdk/src/client.ts, packages/sdk/src/feature.ts, packages/types/src/index.ts
flat objects are now supported.
=> feat: support objects as variables

docs/quick-start.md, docs/sdks.md, packages/core/src/tester.ts, packages/sdk/README.md, packages/sdk/src/client.ts, packages/sdk/src/createInstance.ts, packages/sdk/src/index.ts, packages/sdk/tsconfig.cjs.json, packages/sdk/tsconfig.esm.json
=> feat: Create SDK instance for fetching datafile

docs/features.md, examples/example-1/features/sidebar.yml, examples/example-1/tests/sidebar.spec.yml, packages/core/src/builder.ts, packages/core/src/linter.ts, packages/core/src/traffic.ts, packages/sdk/src/feature.ts, packages/types/src/index.ts
=> feat: Variable overrides at rule level

examples/example-1/features/baz.yml, examples/example-1/features/qux.yml, examples/example-1/tests/baz.spec.yml, examples/example-1/tests/qux.spec.yml, packages/core/src/linter.ts, packages/core/src/tester.ts, packages/types/src/index.ts
- Allow variations to have a description
- Allow 3 decimal places in weights and percentages
- Variations total weight must equal 100
=> fix: linting fixes

docs/features.md, docs/sdks.md, examples/example-1/features/qux.yml, examples/example-1/tests/qux.spec.yml, packages/core/src/linter.ts, packages/sdk/src/client.ts, packages/sdk/src/feature.ts, packages/types/src/index.ts
I really hope nobody needs this, but it's there for unavoidable situations.
=> feat: Introduce new JSON type for variables

Makefile
=> chore: Print SDK size for minified and gzipped versions

docs/segments.md, package-lock.json, packages/core/src/linter.ts, packages/sdk/package.json, packages/sdk/src/conditions.spec.ts, packages/sdk/src/conditions.ts, packages/types/src/index.ts
=> feat: Introduce semver operators

docs/faq.md
This is a very important change.
It's life or death, make or break, now or never.
=> chore: Update typo in FAQ

docs/sdks.md, packages/core/src/tester.ts, packages/sdk/src/client.ts, packages/sdk/src/createInstance.ts, packages/sdk/src/feature.ts, packages/sdk/src/index.ts, packages/sdk/src/logger.ts
=> feat: Introduce logging

docs/sdks.md, packages/sdk/src/client.ts, packages/sdk/src/createInstance.spec.ts, packages/sdk/src/createInstance.ts
Allows merging default attributes from one place.
=> feat: Intercept attributes

package-lock.json, package.json
=> chore: upgrade webpack

docs/sdks.md, packages/sdk/src/client.ts, packages/sdk/src/createInstance.spec.ts, packages/sdk/src/createInstance.ts
=> Refresh datafiles

packages/sdk/README.md
Forgot to trigger minor release via #50
=> feat: refresh datafile

docs/sdks.md, packages/sdk/README.md, packages/sdk/src/client.ts, packages/sdk/src/createInstance.spec.ts, packages/sdk/src/createInstance.ts, packages/sdk/src/emitter.ts
=> feat: Events listener

docs/configuration.md, docs/groups.md, docs/sidebarNavigation.json, examples/example-1/features/bar.yml, examples/example-1/features/qux.yml, examples/example-1/groups/myExclusionGroup.yml, examples/example-1/tests/bar.spec.yml, examples/example-1/tests/qux.spec.yml, packages/core/src/allocator.spec.ts, packages/core/src/allocator.ts, packages/core/src/builder.ts, packages/core/src/config.ts, packages/core/src/linter.ts, packages/core/src/tester.ts, packages/core/src/traffic.spec.ts, packages/core/src/traffic.ts, packages/react/src/activateFeature.spec.tsx, packages/react/src/useSdk.spec.tsx, packages/react/src/useStatus.spec.tsx, packages/react/src/useVariable.spec.tsx, packages/react/src/useVariation.spec.tsx, packages/sdk/src/createInstance.spec.ts, packages/sdk/src/feature.ts, packages/types/src/index.ts
Closes #60 
- Upgrade to latest SDK first, then
- Upgrade to latest CLI for building datafiles
=> feat: Mutually exclusive experiments via Groups

docs/sdks.md, packages/sdk/src/client.ts, packages/sdk/src/createInstance.spec.ts, packages/sdk/src/createInstance.ts, packages/types/src/index.ts
Sticky features support added.
=> feat: sticky features

docs/sdks.md, packages/sdk/src/client.ts, packages/sdk/src/createInstance.spec.ts, packages/sdk/src/createInstance.ts, packages/sdk/src/statuses.ts, packages/types/src/index.ts
Support for initial features before SDK is ready.
=> feat: Initial features

docs/segments.md, examples/example-1/attributes/date.yml, examples/example-1/features/discount.yml, examples/example-1/segments/blackFridayWeekend.yml, examples/example-1/tests/discount.yml, packages/core/src/linter.ts, packages/sdk/src/conditions.spec.ts, packages/sdk/src/conditions.ts, packages/types/src/index.ts
Introduced two new operators:
- `before`
- `after`
See diff for docs and examples.
=> feat: Date comparison operators

examples/example-1/tests/sidebar.spec.yml, packages/sdk/README.md, packages/sdk/src/instance.ts
- new `bucketKeySeparator` option added
- bug fix for bucket key generation (attribute keys were used instead of values 😱)
=> feat: allow bucket key customization

packages/react/README.md
Forgot to trigger minor release via #70 😿
=> feat: allow customizing bucket key

docs/configuration.md, examples/example-1/featurevisor.config.js, packages/core/src/builder.ts, packages/core/src/config.ts, packages/core/src/traffic.spec.ts, packages/types/src/index.ts
New `prettyState` and `prettyDatafile` boolean options in `featurevisor.config.js` file, to allow for pretty printing.
=> feat: Pretty JSON

examples/example-1/features/foo.yml, packages/core/src/linter.ts
This helps produce datafiles in the format `datafile-tag-<tag-name>.json`.
=> feat: allow tags to be lower cased and alphanumeric only

docs/building-datafiles.md, packages/cli/src/index.ts, packages/core/src/builder.ts
```
$ featurevisor build
$ featurevisor build --revision 1.2.3
```
=> feat: allow building datafiles with custom revision flag in CLI

docs/sidebarNavigation.json, docs/use-cases/entitlements.md
Guide for managing user entitlements (permissions) with Featurevisor.
=> docs: entitlements

docs/sidebarNavigation.json, docs/use-cases/testing-in-production.md
=> docs: testing in production

docs/sidebarNavigation.json, docs/use-cases/microfrontends.md
Documentation showing an use case of using Featurevisor in a microfrontends architecture.
=> docs: microfrontends

packages/core/src/linter.ts
=> fix: show linting error only when it fails

docs/cli.md, docs/code-generation.md, docs/sidebarNavigation.json, examples/example-1/.gitignore, examples/example-1/README.md, examples/example-1/package.json, packages/cli/src/index.ts, packages/core/src/generate-code/index.ts, packages/core/src/generate-code/typescript.ts, packages/core/src/index.ts
Generate code from YAMLs in your Featurevisor project.
Docs: https://featurevisor.com/docs/code-generation/
=> feat: code generation

README.md
Trigger a minor release because I forgot the prefix in #109 
Tried adding PRLint via #111, but it's still not creating a new check yet.
=> feat: required features

packages/sdk/src/logger.ts
Thanks to @honzabit for finding the issue first.
=> fix: break in switch statement of logger handler

docs/features.md, packages/core/src/builder.ts, packages/core/src/linter.ts, packages/sdk/src/instance.spec.ts, packages/sdk/src/instance.ts, packages/types/src/index.ts
=> feat: Support deprecating features

docs/integrations/partykit.md, docs/sidebarNavigation.json
Created a guide for integrating [Featurevisor SDK](https://featurevisor.com/docs/sdks/) with [PartyKit](https://partykit.io) for managing realtime updates.
Based on this tweet: https://twitter.com/threepointone/status/1689321601567793169
=> docs: PartyKit + Featurevisor

docs/react-native.md, docs/sidebarNavigation.json
=> docs: React Native

docs/frameworks/nextjs.md, docs/sidebarNavigation.json
Guide for using Featurevisor SDK with Next.js apps.
Covers their Pages Router only for now. New App Router will be handled later.
=> docs: nextjs integration

packages/sdk/src/instance.spec.ts
=> chore: add more tests for sdk

packages/sdk/src/instance.spec.ts
Moves test coverage for the SDK to 92.26%.
=> chore: add tests for sdk

docs/features.md, examples/example-1/features/sidebar.yml, packages/core/src/linter.ts, packages/types/src/index.ts
Like variations, variables can now have `description`.
=> feat: let variables have descriptions

packages/core/src/tester/cliFormat.ts, packages/core/src/tester/testFeature.ts, packages/core/src/tester/testProject.ts, packages/core/src/tester/testSegment.ts
- A lot of unnecessary nesting in tests output removed
- Red and green colours added accordingly to assertions
Learn more about testing here: https://featurevisor.com/docs/testing/
=> chore: tests output made pretty

packages/core/src/site/exportSite.ts
Fix after merging https://github.com/featurevisor/featurevisor/pull/179
=> chore: fix site generator

packages/core/src/builder/buildDatafile.ts
=> fix: do not include variable description in datafiles

packages/core/src/datasource/adapter.ts, packages/core/src/datasource/datasource.ts, packages/core/src/datasource/filesystemAdapter.ts
Forgot the D (for deletes) of CRUD in https://github.com/featurevisor/featurevisor/pull/194
=> feat: the D of CRUD

examples/example-1/tests/qux.spec.yml, packages/core/src/tester/testFeature.ts
=> fix: testing JSON variables in both object and stringified form

packages/site/src/components/HistoryTimeline.tsx
=> fix: entity links from history timeline

examples/example-1/features/showPopup.yml, examples/example-1/segments/qa.yml, examples/example-1/tests/showPopup.spec.yml, packages/core/src/builder/buildDatafile.ts
=> fix: extract segment keys from forced rules

packages/core/src/builder/traffic.ts
=> fix: include variation allocations when introduced later

docs/faq.md, docs/roadmap.md, packages/core/src/linter/featureSchema.ts, packages/core/src/linter/groupSchema.ts
=> feat!: v1.0.0 stable

packages/types/README.md
Because #231 failed to do it :(
=> feat!: trigger v1 release

packages/sdk/src/instance.ts
=> chore: add debug logs to SDK evaluations

examples/example-1/features/foo.yml, examples/example-1/tests/foo.spec.yml, packages/core/src/builder/buildDatafile.ts
=> fix: stringify segments in variable overrides correctly

docs/testing.md, packages/cli/src/index.ts, packages/core/src/tester/testFeature.ts, packages/core/src/tester/testProject.ts
See docs updates below.
```
$ featurevisor test --showDatafile
```
=> feat: showDatafile option when running tests

docs/testing.md, examples/example-1/tests/baz.spec.yml, examples/example-1/tests/germany.spec.yml, packages/core/src/linter/testSchema.ts, packages/core/src/tester/matrix.spec.ts, packages/core/src/tester/matrix.ts, packages/core/src/tester/testFeature.ts, packages/core/src/tester/testSegment.ts, packages/types/src/index.ts
Closes #220 
Once merged and the site is published, you can find the docs at https://featurevisor.com/docs/testing/#matrix
=> feat: Matrix for test specs

packages/site/src/components/ExpandRuleSegments.tsx
=> fix: show string segments in generated site

examples/example-1/tests/foo.spec.yml, packages/sdk/src/instance.ts
=> fix: rule percentage checks are now inclusive of end range

packages/core/src/tester/testProject.ts
- Test runner used to have similar code duplicated for Segment and Feature testing
- Code made DRY so I don't have to keep duplicating my changes in both places
---
This will later help with #237
=> chore: make test runner DRY

docs/features.md, examples/example-1/Makefile, examples/example-1/README.md, examples/example-1/features/showBanner.yml, examples/example-1/package.json, packages/core/src/builder/buildDatafile.ts, packages/core/src/linter/featureSchema.ts, packages/types/src/index.ts
=> feat: allow exposing features with tags + environment combination

docs/feature-management.md, docs/frameworks/astro.md, docs/sdks/browser.md, docs/sdks/index.md, docs/sdks/javascript.md, docs/sdks/nodejs.md, docs/sidebarNavigation.json, docs/use-cases/experiments.md, docs/use-cases/remote-configuration.md
This helps bring more SDKs docs into the site in future.
=> docs: SDK page split up

packages/site/mock/search-index.json, packages/site/src/components/ShowFeature.tsx
=> chore: show tags in site if exposed to tags only

docs/linting.md, packages/cli/src/index.ts, packages/core/src/linter/lintProject.ts
=> feat: lint by key pattern and entity type

examples/example-1/features/baz.yml, packages/site/src/components/ShowFeature.tsx
Fix for https://github.com/featurevisor/featurevisor/issues/262
=> fix(site): properly handle bucketBy.or in feature

docs/sdks/index.md, docs/sdks/roku.md, docs/sidebarNavigation.json
Added a documentation page for the [Roku SDK](https://github.com/featurevisor/featurevisor-roku).
=> docs: add Roku SDK documentation

docs/integrations/cloudflare-pages.md
=> docs: note about automatic deployments

docs/sdks/nodejs.md
Updates based on learnings from https://github.com/featurevisor/featurevisor-example-nodejs/pull/1
Refs https://github.com/featurevisor/featurevisor/issues/269
=> docs: updates to node.js guide

docs/cli.md, packages/cli/src/index.ts, packages/core/src/find-usage/index.ts, packages/core/src/index.ts
See docs in diff.
```
$ npx featurevisor find-usage --segment=my_segment
$ npx featurevisor find-usage --attribute=my_attribute
$ npx featurevisor find-usage --unusedSegments
$ npx featurevisor find-usage --unusedAttributes
```
=> feat: find usage of segments and attributes

docs/glossary.md, docs/sidebarNavigation.json
Added a glossary listing various different terms that users will get exposed to when they adopt Featurevisor.
=> docs: glossary

docs/sidebarNavigation.json, docs/use-cases/deprecation.md
Added new use case guide for deprecating feature flags safely.
=> docs: deprecation

docs/cli.md, packages/cli/src/index.ts, packages/core/src/index.ts, packages/core/src/info/index.ts
New command introduced to show count of various entities:
```
$ npx featurevisor info
```
=> feat: show project info in CLI

packages/core/src/datasource/filesystemAdapter.ts
Instead of `execSync`, use `spawn` to stream the command output.
Otherwise it risks seeing `ENOBUFS` error in Node.js, when exporting site:
```
$ npx featurevisor site export
```
=> fix: use streaming to get full history

packages/sdk/src/bucketer.ts, packages/sdk/src/evaluate.ts, packages/sdk/src/hooks.ts, packages/types/src/bucket.d.ts
- Moved some types to SDK page, which were used by SDK alone
=> chore: move some types to SDK package
