featurevisor/featurevisor

examples/example-1/features/baz.yml
examples/example-1/tests/baz.spec.yml
packages/sdk/src/client.ts

fix: Return defaultVariation when feature cannot be bucketed

---

package-lock.json
packages/sdk/package.json
packages/sdk/src/conditions.ts

Reduces SDK size to 20kB (5.6kB minified and gzipped)

fix: use compare-versions package to reduce sdk bundle size

---

docs/features.md
docs/quick-start.md
examples/example-1/features/bar.yml
examples/example-1/features/baz.yml
examples/example-1/features/foo.yml
examples/example-1/features/qux.yml
examples/example-1/features/sidebar.yml
packages/core/src/builder.ts
packages/core/src/linter.ts
packages/core/src/traffic.spec.ts
packages/react/src/activateFeature.spec.tsx
packages/react/src/useSdk.spec.tsx
packages/react/src/useStatus.spec.tsx
packages/react/src/useVariable.spec.tsx
packages/react/src/useVariation.spec.tsx
packages/sdk/src/createInstance.spec.ts
packages/types/src/index.ts

```yml
variations:
- type: boolean
value: true
weight: 100
- type: boolean
value: false
weight: 0
```
```yml
variations:
- value: true
weight: 100
- value: false
weight: 0
```

fix: do not require variation type in Feature's YAML

---

packages/sdk/src/instance.ts

The deleted types exist already in `emitter.ts` file.

fix: remove duplicate redundant types

---

examples/example-1/features/discount.yml
examples/example-1/featurevisor.config.js
packages/cli/src/index.ts
packages/core/src/builder.ts
packages/core/src/traffic.spec.ts
packages/core/src/traffic.ts
packages/types/src/index.ts

Every time a datafile is built against environment/tag combination against a revision (version), it generates a corresponding state file.
Read about state files here: https://featurevisor.com/docs/state-files/
It works well as long as there are no overlaps of features across multiple tags.
Meaning, as long as same feature does not belong to multiple tags.
It is still alright, as long as multiple tags are added to the feature when the feature is first created. But if a feature starts with one tag, and then another new tag is added to it much later, the bucketing info will not match anymore across multiple state files which are built against environment/tag combo and not against an environment alone.
State files are now generated against a single environment only and not taking tags into …

feat: state files are now per environment

---

examples/example-1/features/foo.yml
examples/example-1/features/sidebar.yml
packages/core/src/linter.ts

Linting made stricter by checking against available keys.
- Only available Attribute keys are allowed in conditions inside Segments and Features
- Only available Feature keys are allowed in Groups' slots
- Only available Segment keys are allowed in Feature rules
Read more about it here: https://featurevisor.com/docs/linting-yamls/

feat: Linting based on available keys

---

packages/core/src/allocator.spec.ts
packages/core/src/allocator.ts
packages/core/src/builder.ts
packages/core/src/traffic.spec.ts
packages/core/src/traffic.ts
packages/sdk/src/feature.ts
packages/sdk/src/index.ts
packages/types/src/index.ts

Generated datafiles would contain bucketed range info in this shape:
```js
{
start: 0,
end: 100000
}
```
With more and more features and their bucketed ranges, it will grow big over time.
Instead of objects, they are now expressed as tuples which will have a positive impact in generated datafile going foward reducing its size.
```js
[0, 100000]
```
SDK is kept backwards compatible so it won't break your application.
You are advised to updated to latest SDK first, before generating new datafiles with latest version of Featurevisor CLI.

feat: ranges in datafiles as tuples

---

docs/features.md
packages/core/src/linter.ts
packages/sdk/README.md
packages/sdk/src/instance.spec.ts
packages/sdk/src/instance.ts
packages/types/src/index.ts

Feature's `bucketBy` property can now accept `or` conditional attribute keys.
And a new `configureBucketKey` option is added, which also helps with testing.
The `bucketBy` property is used to determine how the feature will be bucketed. Meaning, how the variation of a feature is assigned to a user.
```yml
bucketBy: userId
```
Given we used `userId` attribute as the `bucketBy` value, it means no matter which application or device the user is using, as long as the `userId` value is the same, the same variation of the feature will be consistently assigned to that particular user.
If you want to bucket users against multiple attributes together, you can do as follows:
```yml
bucketBy:
- organizationId
- userId
```
If you want to bucket users against first available attribute only, you can do …

feat: make bucketing key configurable

---

packages/core/src/traffic.ts

Ranges like `[0, 0]` will not appear in datafiles any more, reducing its size.
Think of variations with weights of `0`.

feat: omit empty ranges in datafile

---

packages/core/src/linter.ts

This will fail linting if anyone names any of their variable keys `variation`, to help avoid any confusion.

feat: do not allow "variation" as variable key

---

docs/use-cases/microfrontends.md

I'd potentially also add a section that featurevisor could be consumed from a microfrontend discovery service, too. This way, you would not need to consume it within a microfrontend (but, of course, for whatever reason one might still do that).
In many cases just disabling or enabling the microfrontend for certain users might be sufficient and the most consistent way of dealing with functionality. (One of many examples: https://youtu.be/Oc2ohxEpUpA?t=2176)

docs: Added Piral to MF Documentation

---

docs/cli.md
docs/state-files.md
packages/cli/src/index.ts
packages/core/src/index.ts
packages/core/src/restore.ts

New CLI command introduced:
```
$ featurevisor restore
```
Equivalent of:
```
$ git checkout -- .featurevisor/
```
It will automatically use the state files directory path based on `featurevisor.config.js`.

feat: restore state files

---

packages/core/src/init.ts

Following the instructions on https://featurevisor.com/docs/quick-start/, at some point the CLI let me run `npm ci` on a project that doesn't have the `package-lock.json` file just yet (documentation says to run `npm install` actually`).

fix: "npm ci" → "npm install" message on project setup

---

packages/sdk/src/instance.ts

Since https://github.com/fahad19/featurevisor/pull/104, variations are string type only.
Therefore we don't need type specific `activate()` methods.

feat: drop type specific activate methods

---

docs/testing.md
examples/example-1/tests/germany.spec.yml
packages/core/src/linter.ts
packages/core/src/tester.ts
packages/types/src/index.ts

In segments' test specs, `expected` has been renamed to `expectedTomatch`.
```yml
tests:
- segments:
- key: germany
assertions:
- context:
country: de
expected: true # notice this line
```
```yml
tests:
- segments:
- key: germany
assertions:
- context:
country: de
expectedToMatch: true # renamed property here
```

feat: segment testing assertion property updated

---

packages/sdk/src/instance.ts

We already had a `getFeature()` method that was private to the SDK instance itself.
Now it is made public, and others can call it as:
```js
sdk.getFeature(featureKey);
```
This will give you the Feature object as found in the datafile, otherwise `undefined`.

feat: make getFeature() method public

---

packages/react/src/useStatus.ts

Ended up with this error when trying to implement Featurevisor SDK in a fresh new React app: https://stackoverflow.com/questions/53472795/uncaught-error-rendered-fewer-hooks-than-expected-this-may-be-caused-by-an-acc
Removing the early return fixed the problem for `useStatus` hoko.

fix: useStatus React hook

---

docs/quick-start.md

Fixed a typo on the datafileUrl variable in the quick-start.md file.

docs(quick-start): fix datafileUrl typo

---

docs/react.md
docs/vue.md
packages/react/README.md
packages/react/src/FeaturevisorProvider.tsx
packages/react/src/activateFeature.spec.tsx
packages/react/src/useFlag.spec.tsx
packages/react/src/useSdk.spec.tsx
packages/react/src/useStatus.spec.tsx
packages/react/src/useVariable.spec.tsx
packages/react/src/useVariation.spec.tsx
packages/vue/README.md

This affects `@featurevisor/react` package only.
```js
import React from "react";
import { createInstance } from "@featurevisor/sdk";
import { FeaturevisorProvider } from "@featurevisor/react";
const f = createInstance({
datafileUrl: "...",
});
function Root() {
return (
<FeaturevisorProvider sdk={f}>
<App />
</FeaturevisorProvider>
);
}
```
`sdk` prop changed to `instance`.
```js
import React from "react";
import { createInstance } from "@featurevisor/sdk";
import { FeaturevisorProvider } from "@featurevisor/react";
const f = createInstance({
datafileUrl: "...",
});
function Root() {
return (
<FeaturevisorProvider instance={f}>
<App />
</FeaturevisorProvider>
);
}
```

feat: React provider component prop renamed from sdk to instance

---

README.md
docs/code-generation.md
docs/examples.md
docs/quick-start.md
docs/sdks.md
docs/tracking/google-analytics.md
docs/use-cases/entitlements.md
docs/use-cases/experiments.md
docs/use-cases/microfrontends.md
docs/use-cases/remote-configuration.md
docs/use-cases/testing-in-production.md

Featurevisor SDK instances are now referred to as `f` instead of `sdk` in the docs.

docs: changed sdk variable name to f

---

docs/sdks.md
packages/sdk/README.md
packages/sdk/src/instance.spec.ts
packages/sdk/src/instance.ts

For convenience, a new `onReady()` method has been added.
```js
import { createInstance } from "@featurevisor/sdk";
const f = createInstance({
datafileUrl: "https://cdn.yoursite.com/datafile.json",
});
f.onReady(() => console.log("SDK is ready!"));
```
I was annoyed wrapping traditional callbacks with Promises when integrating Featurevisor SDK with Next.js when doing server-side rendering.

feat: onReady method for SDK as Promise

---

packages/sdk/src/conditions.spec.ts

Improves unit tests coverage by testing all the operators.

chore: add tests for operators in SDK

---

package-lock.json
package.json
packages/cli/.prettierignore
packages/core/.prettierignore
packages/react/.prettierignore
packages/sdk/.prettierignore
packages/site/.prettierignore
packages/types/.prettierignore
packages/vue/.prettierignore

Used `feat:` to trigger a new publish of all packages, which we couldn't do in last PR merge because of Prettier 3.x issues with Lerna: https://github.com/fahad19/featurevisor/actions/runs/6090195862/job/16524588061#step:10:32

feat: use Prettier v2.x

---

docs/testing.md
examples/example-1/tests/bar.spec.yml
examples/example-1/tests/baz.spec.yml
examples/example-1/tests/discount.spec.yml
examples/example-1/tests/foo.spec.yml
examples/example-1/tests/germany.spec.yml
examples/example-1/tests/qux.spec.yml
examples/example-1/tests/redesign.spec.yml
examples/example-1/tests/sidebar.spec.yml
examples/example-json/tests/netherlands.segment.json
examples/example-json/tests/showCookieBanner.feature.json
examples/example-toml/tests/netherlands.segment.toml
examples/example-toml/tests/showCookieBanner.feature.toml
examples/example-yml/tests/netherlands.segment.yml
examples/example-yml/tests/showCookieBanner.feature.yml
packages/core/src/builder.ts
packages/core/src/datasource/datasource.ts
packages/core/src/linter.ts
packages/core/src/tester.ts
packages/types/src/index.ts

Test specs used to be nested too much, and this happened because feature testing was introduced first, and the same API was later used to also support segments testing: https://featurevisor.com/docs/testing/
This approached helped achieve the result, but not in a very readable way.
Now with the proposed changes they are much more readable, and easy to follow and does not require one to build the datafiles on disk to run tests. The datafiles, when running tests, will be built on the fly without changing anything on disk.
```yml
tests:
- segments:
- key: netherlands
assertions:
- context:
country: nl
expectedToMatch: true
- context:
country: de
someOtherAttribute: someOtherValue
expectedToMatch: false
- context:
country: notNl
expectedToMatch: false
```
```yml
segment: netherlands …
```

feat: test specs improvements

---

.github/workflows/checks.yml
.github/workflows/publish.yml

As a slight improvement, I have set the `actions/setup-nod@v2` GH action to read the node version directly from the `.nvmrc` file. 
This will guarantee that the versions will be updated in future iterations only in a single place. 
Cheers ❤️

chore: Set single Nodejs version source

---

docs/cli.md
examples/example-1/package.json
examples/example-json/package.json
examples/example-toml/package.json
examples/example-yml/package.json
packages/cli/src/index.ts
packages/core/src/find-duplicate-segments/findDuplicateSegments.ts
packages/core/src/find-duplicate-segments/index.ts
packages/core/src/index.ts

It is possible to end up with multiple segments having same conditions in larger projects. This is not a problem per se, but we should be aware of it.
We can find these duplicates early on by running:
```
$ featurevisor find-duplicate-segments
```

feat: find duplicate segments from CLI

---

examples/example-1/package.json
packages/cli/src/index.ts
packages/core/src/builder/buildDatafile.ts
packages/core/src/builder/buildProject.ts
packages/core/src/builder/getFeatureRanges.ts
packages/core/src/datasource/datasource.ts
packages/core/src/find-duplicate-segments/findDuplicateSegments.ts
packages/core/src/find-duplicate-segments/index.ts
packages/core/src/generate-code/index.ts
packages/core/src/generate-code/typescript.ts
packages/core/src/linter/checkCircularDependency.ts
packages/core/src/linter/groupSchema.ts
packages/core/src/linter/lintProject.ts
packages/core/src/restore.ts
packages/core/src/site/exportSite.ts
packages/core/src/site/generateSiteSearchIndex.ts
packages/core/src/tester/testFeature.ts
packages/core/src/tester/testProject.ts
packages/core/src/tester/testSegment.ts

Datasource is synchronous, and uses the filesystem directly.
To keep PRs incremental and relatively small, this is the first PR to make datasource methods async.
Future PRs will tackle:
- All read/write operations happening via Datasource instance
- Custom parser API to include both `parse` and `stringify` functions
- Datasource will introduce an adapter pattern, where Filesystem will be one of them (used as default)
- Datasource instance will be passed from CLI runner directly
This is NOT a breaking change in anyway, and is only affecting the internals.

chore: make datasource async

---

packages/cli/src/index.ts
packages/core/src/builder/buildProject.ts
packages/core/src/dependencies.ts
packages/core/src/find-duplicate-segments/index.ts
packages/core/src/generate-code/index.ts
packages/core/src/generate-code/typescript.ts
packages/core/src/index.ts
packages/core/src/linter/lintProject.ts
packages/core/src/restore.ts
packages/core/src/site/exportSite.ts
packages/core/src/site/generateSiteSearchIndex.ts
packages/core/src/site/serveSite.ts
packages/core/src/tester/testProject.ts

Dependencies like project config and datasource instance are injected from one place now (CLI runner).
This helps `core` package not have to deal with too many implementation details.
A continuation of #175

chore: inject dependencies from CLI runner

---

examples/example-yml-include/.gitignore
examples/example-yml-include/README.md
examples/example-yml-include/attributes/country.yml
examples/example-yml-include/attributes/deviceId.yml
examples/example-yml-include/attributes/userId.yml
examples/example-yml-include/features/rules/showCookieBanner-everyone.yml
examples/example-yml-include/features/rules/showCookieBanner-nl.yml
examples/example-yml-include/features/showCookieBanner.yml
examples/example-yml-include/featurevisor.config.js
examples/example-yml-include/package.json
examples/example-yml-include/segments/netherlands.yml
examples/example-yml-include/tests/netherlands.segment.yml
examples/example-yml-include/tests/showCookieBanner.feature.yml
package-lock.json
packages/core/src/config/parsers.ts
packages/core/src/datasource/filesystemAdapter.ts

It is possible that a certain feature definition can grow really large, especially with too many rules against its multiple environments.
This PR makes a small change in custom parser API to pass `filePath`, if using filesystem adapter.
And from individual Featurevisor project's config level, we can expand the YAML parser with `!include` tag for including YAML content from other files, thus breaking a large file into smaller ones.
See more in the branch's [`examples/example-yml-include`](https://github.com/featurevisor/featurevisor/tree/yml-include/examples/example-yml-include) directory.
```yml
description: Show cookie banner to users from the Netherlands
tags:
- all
bucketBy: userId
environments:
staging:
rules:
- key: "everyone"
segments: "*" # enabled for everyone in staging only …
```

feat: YAML includes support with example project

---

package-lock.json
package.json
packages/site/.eslintrc.js
packages/site/mock/search-index.json
packages/site/package.json
packages/site/postcss.config.js
packages/site/public/index.html
packages/site/src/components/SearchInput.tsx
packages/site/src/index.css
packages/site/src/index.tsx
packages/site/tailwind.config.js
packages/site/tsconfig.cjs.json
packages/site/types/assets.d.ts
packages/site/types/styles.d.ts
packages/site/webpack.common.js
packages/site/webpack.dev.js
packages/site/webpack.prod.js
tools/getWebpackConfig.js

When I started working on https://github.com/featurevisor/featurevisor/issues/36 I've realised that a development specific workflow was needed in order to be able to easily modify featurevisor site. This is a PR preceding the actual issue.
Add development mode configuration:
* Introduce webpack development mode, for local site development using `webpack-dev-server`
* Add `mock/search-index.json` - a mock response for the search index data
* Shared, development, and production webpack configuration
Update site production build configuration: 
* Update css build process, by including it in the webpack build using `postcss-loader`
* Copy assets from public folder to the build folder
* Automatically inject `.js` file generated from the bundle in the `index.html`
* Add typescript types for …

chore: update webpack config for site build & local dev

---

packages/core/src/builder/buildProject.ts
packages/core/src/datasource/adapter.ts
packages/core/src/datasource/datasource.ts
packages/core/src/datasource/filesystemAdapter.ts

The responsibilities of writing datafiles to disk has been moved to Datasource adapter level, leaving CLI runners simple even if internal implementations change in future.
See the impact of this change in `buildProject.ts` file.

chore: move datafile writing to datasource level

---

package-lock.json
packages/site/src/components/HistoryTimeline.tsx
packages/site/src/components/ListAttributes.tsx
packages/site/src/components/ListFeatures.tsx
packages/site/src/components/ListSegments.tsx
packages/site/src/components/SearchInput.tsx
packages/site/src/components/ShowAttribute.tsx
packages/site/src/components/ShowFeature.tsx
packages/site/src/components/ShowSegment.tsx
packages/site/src/hooks/searchIndexHook.ts
packages/site/src/hooks/useSearch.ts
packages/site/src/hooks/useSearchIndex.ts
packages/site/src/utils/index.ts

We want to be able to share the url and deeplink to the page shared. For that purpose we need to persist the search params in the url. Read the url, extract the search query and load the correct view.
**Changes:**
* Add `useSearch` hook responsible for:
* read/write search params from the url
* parse url query to query object
* generate features, segments, attributes based on parsed query object
* `SearchInput` component sets the search input to the url (through `useSearch` hook)
* Features, Segments, Attributes views read the respective data from `useSearch` hook
**Preview:**
https://github.com/featurevisor/featurevisor/assets/1969742/f2610257-ad28-449b-96fe-dbc65007d7e6
https://github.com/featurevisor/featurevisor/issues/36

feat: add deep linking, persist search in url

---

packages/core/src/site/exportSite.ts
packages/core/src/site/generateHistory.ts
packages/core/src/site/generateSiteSearchIndex.ts

We used to show `n/a` in place of `Last modified` section in list view of generated site: https://featurevisor.com/docs/site/
This issue was likely introduced when introducing #158.

fix: last modified info in generated site

---

examples/example-1/features/checkout.yml
examples/example-1/tests/checkout.spec.yml
packages/sdk/src/feature.ts
packages/sdk/src/instance.spec.ts

When matching both the `Traffic` (rule equivalent in generated datafiles) and their `Allocation`, it used to always check if an `Allocation` is found or not in the Traffic itself.
This was problematic because not all features have variations.
Resulting into issues when evaluating variables (in features with no variations) which have overrides from rule level, because SDK never found any allocation info for them (since they had no variations).
When matching both Traffic and Allocation, it will return:
- `Traffic` if segments matched (irrespective of Allocation bucket range checks), and
- `Allocation` if bucket range checks are satisfied
Tests are available in both YAML specs in example project, and also unit tests at SDK level.
Big thanks to @pawdat for his investigation in #187, wouldn't …

fix: evaluate variables overridden from rules with no variations

---

packages/site/src/components/App.tsx
packages/site/src/components/ShowFeature.tsx
packages/site/src/components/Tabs.tsx

This PR adds three small site navigation improvements
1. Initial auto-redirect to `/features` (it was working only on the page, not in the URL)
2. Auto-select first environment in Features _Rules_ and _Forces_ pages
3. Keep _Rules_ and _Forces_ tabs selected when navigating into an environment

feat: small site navigation improvements

---

examples/example-1/features/hidden.yml
packages/site/src/components/ShowFeature.tsx
packages/site/src/utils/index.ts

Featurevisor allows hiding features from being included in specific environment datafiles using the `expose` property: https://featurevisor.com/docs/features/#expose
If `expose` was set to `false`, the generated site would not show this info anywhere.
Now it shows a warning:

fix: show warning in site when rules are not exposed

---

packages/core/src/datasource/adapter.ts
packages/core/src/datasource/datasource.ts
packages/core/src/datasource/filesystemAdapter.ts

**NOTE**: Only internal APIs have changed, without breaking anything for consumers.
- Datasource adapter interface now handles all CRUD methods
- New `writeEntity` method introduced in Adapter
- `parseEntity` method is now `readEntity`, since parsing is an internal implementation details not needed to be exposed to Datasource consumers

feat: datasource adapters now handling full CRUD

---

examples/example-1/attributes/version.yml
examples/example-1/features/footer.yml
examples/example-1/segments/version_5.5.yml
examples/example-1/tests/footer.spec.yml
packages/core/src/utils.ts
packages/sdk/src/segments.spec.ts
packages/sdk/src/segments.ts

The bug was in datafile builder, which did not manage to extract segment keys which were used via `not` operator in the feature's rules.
SDK remains unaffected.

fix: using not operator in feature rules

---

docs/testing.md
packages/cli/src/index.ts
packages/core/src/tester/testFeature.ts
packages/core/src/tester/testProject.ts
packages/core/src/tester/testSegment.ts
packages/sdk/src/instance.ts

Closes #209 and #210 
Featurevisor tests can be now run with some additional options in CLI:
```
$ featurevisor test
$ featurevisor test --keyPattern="myFeatureKey|mySegmentKey"
$ featurevisor test --keyPattern="myFeatureKey|mySegmentKey" --assertionPattern="assertion description"
$ featurevisor test --verbose
```
If you are using `featurevisor test` as an npm script like:
```js
// package.json
{
"scripts": {
"test": "featurevisor test"
}
}
```
Then do:
```
$ npm test -- --keyPattern="myKeyHere"
```

feat: filter tests and support verbosity for debugging

---

packages/core/src/linter/attributeSchema.ts
packages/types/src/index.ts

Closes #205
- Fixes linting issue for checking attribute types
- Introduces new `semver` attribute type, making way for #208 
Not a breaking change in any way.

feat: attribute type for semver

---

packages/core/src/linter/featureSchema.ts
packages/core/src/linter/testSchema.ts

Closes #218 
- Feature's rules must have a `percentage` property
- Test assertions should require certain properties too
Treated as a `feat` because if some existing users were defining the entities without the properties that are made required via this PR, it will fail their build. Which is a good thing.

feat: require certain fields in features and tests when linting

---

examples/example-1/features/foo.yml
examples/example-1/tests/foo.spec.yml
packages/sdk/src/feature.ts
packages/sdk/src/instance.spec.ts
packages/sdk/src/instance.ts

- Features can have variations: https://featurevisor.com/docs/features/#variations
- Variations can have variables: https://featurevisor.com/docs/features/#variable-types
- Furthermore, those variables inside variations can have overrides: https://featurevisor.com/docs/features/#overriding-variables
Forcing:
- Variations can be forced: https://featurevisor.com/docs/features/#force
When forcing a variation from rules, without forcing variables, the forced variation is not honoured when evaluating its variables.
When evaluating variables, it will now check if there happens to be any forced variation.
If any forced variation, it will then honour the variation value before evaluating the variable values.
Otherwise, it will continue with its regular bucketing logic.
- Issue has been reproduced …

fix: forcing variation with variable overrides

---

examples/example-1/features/foo.yml
packages/site/mock/search-index.json
packages/site/src/components/ShowFeature.tsx

We generate a static read-only site based on Git repo's content: https://featurevisor.com/docs/site/
When rendering variables under Rules, we didn't stringify the value and it was often showing as an empty string.
Because `{true}` in React's JSX is empty string.
We stringify the values so they appear in a way that's readable to end users.
Mock data in `site` package was copied from example-1 project's output.

fix: stringify variable value when rendering in generated site

---

packages/core/src/tester/matrix.ts
packages/core/src/tester/prettyDuration.ts
packages/core/src/tester/printTestResult.ts
packages/core/src/tester/testFeature.ts
packages/core/src/tester/testProject.ts
packages/core/src/tester/testSegment.ts
packages/types/src/index.ts

We have a test runner: https://featurevisor.com/docs/testing/
- Get a summary of all tests passed/failed
- Get duration info at assertion level, and also at whole test level
This will help with #237 later.

chore: show duration in test runner

---

docs/building-datafiles.md
packages/core/src/builder/buildProject.ts
packages/core/src/tester/index.ts
packages/core/src/tester/testFeature.ts

You can print the contents of a datafile for a single feature without writing anything to disk by passing these flags:
```
$ featurevisor build --feature=foo --environment=production --print --pretty
```
This is useful primarily for debugging and testing purposes.
If you are an SDK developer in other languages besides JavaScript, you may want to use this handy command to get the generated datafile content in JSON format that you can use in your own test runner.

feat: print feature datafile

---

docs/site.md
packages/site/src/utils/index.ts

https://featurevisor.com/docs/site/
Previously existing:
- `my keyword`: plain search
- `tag:my-tag`: search features by tag
- `in:production`: search features by environment
- `archived:true` or `archived:false`
- `capture:true` or `capture:false`: for filtering attributes
New additions:
- `with:variations` or `without:variations`: for filtering features with/without variations
- `variation:variation-value`: for filtering features by variation value
- `with:variables` or `without:variables`: for filtering features with/without variables
- `variable:variable-key`: for filtering features by variable key

feat: additional advanced search options in generated site

---

packages/core/src/linter/printError.ts
packages/core/src/linter/testSchema.ts

Before, you could mistakenly pass strings as values in a matrix, like:
```yml
feature: my
assertions:
- matrix:
environment: [production]
at: [85, 90]
country: [nl]
city: [amsterdam, utrecht]
somethingWithWrongValue: wrong value here # see here
at: ${{ at }}
environment: ${{ environment }}
context:
country: ${{ country }}
city: ${{ city }}
expectedToBeEnabled: false
```
Linting made stricter to pick this kind of issues up early.
Zod error printer updated to handle union errors in a more user friendly way.

fix: linting should pick up non-array matrix values in tests

---

packages/core/src/linter/lintProject.ts

We have linting for entity (like feature, segment, attribute) content: https://featurevisor.com/docs/linting/
It never checked for the validity of the entity's own name (which is derived from the file name).
When someone mistakenly adds a space to the filename, it's hard to figure out manually.
Now it checks the entity name as well, and shows linting error message if any.
Currently allows only alphanumeric characters for entities, along with `_`, `-, and `.`.

fix: lint entity names

---

docs/testing.md
packages/cli/src/index.ts
packages/core/src/builder/buildDatafile.ts
packages/core/src/tester/testFeature.ts
packages/core/src/tester/testProject.ts

We have a test runner: https://featurevisor.com/docs/testing/
It iterates through each spec at a time, and for each feature/environment it generates a datafile on the fly before asserting its expectations.
Meaning, for each feature assertion, it generates a new datafile on the fly.
Without changing any existing behaviour, any new CLI option is introduced that will generate the datafiles for test runner early packing all the features for each environment, avoiding the need for generating datafiles too many times.
```
$ npx featurevisor test --fast
```
Without this new `--fast` option, it will continue to behave like it does now.
The idea is that this new test runner option would drastically reduce the time taken for all tests to complete in a Featurevisor project, especially those having …

feat: allow option to test by generating datafiles early

---

docs/frameworks/nextjs.md

Updated next js docs for app router https://github.com/featurevisor/featurevisor-example-nextjs/blob/main/src/app/approuter/page.tsx

docs: updated next js docs to include app router example

---

docs/building-datafiles.md
packages/core/src/builder/buildDatafile.ts
packages/core/src/builder/buildProject.ts
packages/core/src/tester/testFeature.ts

Generate and print datafile content on the fly for both specific feature and also all features in a given environment, without affecting any state on the disk.
We could only do:
```
$ featurevisor build --feature=foo --environment=production --print --pretty
```
Now, we can also print datafile for a specific environment (containing all its features):
```
$ featurevisor build --environment=production --print --pretty
```

feat: allow printing datafile per environment

---

docs/testing.md
packages/cli/src/index.ts
packages/core/src/tester/testProject.ts

Additional option for showing only failed test specs when running tests:
```
$ featurevisor test --onlyFailures
```
More info: https://featurevisor.com/docs/testing/

feat: allow showing only failed specs in test runner

---

packages/cli/src/index.ts

Pass `rootDirectoryPath` directly, without needing to prepare project dependencies.
Otherwise it wasn't allowing users to `init` a fresh new project.
```
$ npm install -g @featurevisor/cli
$ mkdir my-featurevisor-project && cd my-featurevisor-project
$ featurevisor init
```
```
$ mkdir my-featurevisor-project && cd my-featurevisor-project
$ npx @featurevisor/cli init
```

fix: init command

---

README.md
docs/building-datafiles.md
docs/cli.md
docs/code-generation.md
docs/deployment.md
docs/integrations/cloudflare-pages.md
docs/integrations/github-actions.md
docs/linting.md
docs/quick-start.md
docs/site.md
docs/state-files.md
docs/testing.md
docs/use-cases/microfrontends.md
packages/cli/README.md
packages/core/src/builder/buildProject.ts
packages/core/src/builder/revision.spec.ts
packages/core/src/builder/revision.ts
packages/core/src/datasource/adapter.ts
packages/core/src/datasource/datasource.ts
packages/core/src/datasource/filesystemAdapter.ts

Featurevisor's build system relied on the `version` found in `package.json` for the generated datafiles' `revision` property.
Links for further understanding:
- https://featurevisor.com/docs/building-datafiles/
- https://featurevisor.com/docs/state-files/
- https://featurevisor.com/docs/deployment/
- https://featurevisor.com/docs/integrations/github-actions/
For every new successful build, it meant incrementing the version number as found in `package.json`.
Many npm projects rely on caching their dependencies, and the cache is busted if the hash of `package.json` and/or `package-lock.json` changes.
If we keep updating the `version` in `package.json` for every build, this way of caching becomes redundant. We don't want that.
Now the revision info is stored next to [state …

feat: revisioning info moved to its own file

---

docs/frameworks/fastify.md
docs/frameworks/nextjs.md
docs/sidebarNavigation.json

Fastify example repo is not available yet. I'll add it once it's up. Meanwhile, check out this complete working app https://github.com/jagadeeshgade008/featurevisor-example-fastify.

docs: Fastify integration

---

examples/example-1/features/showHeader.yml
examples/example-1/segments/desktop.yml
examples/example-1/segments/version_gt5.yml
examples/example-1/tests/showHeader.spec.yml
packages/core/src/tester/testSegment.ts
packages/sdk/src/conditions.spec.ts
packages/sdk/src/conditions.ts
packages/sdk/src/feature.ts
packages/sdk/src/instance.ts
packages/sdk/src/segments.spec.ts
packages/sdk/src/segments.ts

- Featurevisor lets you define rules against environments for your features: https://featurevisor.com/docs/features/#rules
- Rules can have multiple segments defined: https://featurevisor.com/docs/features/#segments
- Segments are conditions against attributes, which may include semver operators: https://featurevisor.com/docs/segments/#semver-equals
- First rule that matches always wins during evaluation
When a wrong semver value is passed in context:
- SDK stops evaluating all further rules if parsing semver in current rule fails, and 
- returns `false` without crashing the app
- while logging the error to console
If semver value (even if it is in wrong format and) causes the parser to fail horribly, we want it to skip that rule and continue processing other rules in a sequential order. …

fix: move to next condition if parsing fails

---

.github/workflows/checks.yml
.github/workflows/publish.yml
docs/integrations/cloudflare-pages.md
docs/integrations/github-actions.md

Bumps GitHub Actions dependencies to latest, and Node version to 20. Resolves #282

Bump GitHub action dependencies

---

docs/deployment.md
docs/integrations/cloudflare-pages.md
docs/integrations/github-pages.md
docs/sidebarNavigation.json

Hi @fahad19,
I've been working on a new guide for setting up Featurevisor with GitHub Pages and I think it's ready to be shared with the world. This guide walks you through the process of setting up continuous integration and deployment of your Featurevisor project with GitHub Actions and GitHub Pages.
Why GitHub Pages, you ask? Well, it's a great alternative to the Cloudflare setup. Not everyone has a Cloudflare account, and not everyone wants to manage one. GitHub Pages, on the other hand, is available to all GitHub users, so it's a bit more accessible. Plus, you don't have to manage environment secrets, which is a nice bonus.
I've also made sure to streamline the process as much as possible. For example, I've removed the "Sequential builds" step from the Cloudflare guide because it's …

GitHub Pages Setup Guide

---

docs/configuration.md
examples/example-1/featurevisor.config.js
packages/core/src/builder/buildDatafile.ts
packages/core/src/builder/traffic.ts
packages/core/src/config/projectConfig.ts

More info in docs (see diff).
A new optional `stringify` property introduced in project configuration for controlling the stringification behaviour of segments and conditions in generated datafiles.
```js
// featurevisor.config.js
module.exports = {
environments: ["staging", "production"],
tags: ["web", "ios", "android"],
// optional
stringify: false // true by default
};
```

feat: introduce new project config stringify

---

docs/cli.md
packages/cli/src/index.ts
packages/core/src/benchmark/index.ts
packages/core/src/index.ts

Introduced an option to benchmark feature/variation/variable evaluations from CLI.
Read more in docs (in diff).
To run benchmarking for a feature:
```
$ npx featurevisor benchmark \
--environment=production \
--feature=foo \
--context='{"country":"de","userId":"123","device":"mobile"}' \
--n=1000000
```
Output will be similar to this:
```
Running benchmark for feature "foo"...
Building datafile containing all features for "production"...
Datafile build duration: 16ms
...SDK initialized
Against context: {"country":"de","userId":"123","device":"mobile"}
Evaluating flag 1000000 times...
Evaluated value : true
Total duration  : 1s 992ms
Average duration: 0.001992ms
```

feat: benchmarking option in CLI

---

docs/cli.md
packages/cli/src/index.ts
packages/core/src/evaluate/index.ts
packages/core/src/index.ts
packages/core/src/utils/index.ts
packages/core/src/utils/pretty.ts
packages/sdk/src/feature.ts
packages/sdk/src/instance.ts

For debugging purposes, a new command has been introduced:
```
$ npx featurevisor evaluate \
--environment=production \
--feature=my_feature \
--context='{"userId": "123", "country": "nl"}'
```
To print as JSON:
```
$ npx featurevisor evaluate \
--environment=production \
--feature=my_feature \
--context='{"userId": "123", "country": "nl"}' \
--print \
--pretty
```

feat: evaluate features in CLI

---

docs/cli.md
packages/cli/src/index.ts
packages/core/src/assess-distribution/index.ts
packages/core/src/index.ts
packages/core/src/utils/pretty.ts

A new command has been introduced in CLI.
See docs in diff for more info.
```
$ npx featurevisor assess-distribution \
--environment=production \
--feature=sidebar \
--context='{"country": "nl"}' \
--populateUuid=userId \
--n=1000
Assessing distribution for feature: "sidebar"...
Building datafile containing all features for "production"...
Datafile build duration: 19ms
...SDK initialized
Evaluating 1,000 times...
Flag evaluations:
- enabled:  	1,000 	100.00%
- disabled: 	    0 	  0.00%
Variation evaluations:
- treatment: 	896 	 89.60%
- control:   	104 	 10.40%
```
Adding `--verbose` helps see the final merged `context` that is passed to SDK for each evaluation:
```
$ npx featurevisor assess-distribution \
--environment=production \
--feature=sidebar \
--context='{"country": "nl"}' \ …
```

feat: assess traffic distribution via CLI

---

packages/site/src/utils/index.ts

Featurevisor supports generating a static site serving as a read-only dashboard: https://featurevisor.com/docs/site/
When searching for features, it wasn't honouring upper cased characters when input in the search bar.
When applying the filtering, it will now lowercase everything so that search results are returned as intended.

fix: search features by any case in generated site

---

docs/cli.md
packages/cli/src/index.ts
packages/core/src/find-duplicate-segments/findDuplicateSegments.ts
packages/core/src/find-duplicate-segments/index.ts

We have a command for finding segments with same conditions as other segments:
```
$ npx featurevisor find-duplicate-segments
```
More info: https://featurevisor.com/docs/cli/#find-duplicate-segments
A new `--authors` option has now been introduced, to also show who are the people who modified the affected segments.
The information is extracted from Git repository's history:
```
$ npx featurevisor find-duplicate-segments --authors
```

feat: find duplicate segments with authors info

---

docs/cli.md
packages/cli/src/index.ts
packages/core/src/evaluate/index.ts
packages/sdk/src/instance.ts

SDK evaluation reason expanded with a new reason `no_match`.
This reason is used when evaluation logic cannot not match with any specific rule against given context.
We allow evaluating features in CLI already: https://featurevisor.com/docs/cli/#evaluate
A new `--verbose` option has been introduced that will print SDK logs for debugging even better, if needs arise.

feat: allow evaluating in CLI with more verbosity

---

docs/configuration.md
examples/example-1/features/footer.yml
examples/example-1/features/redesign.yml
examples/example-1/featurevisor.config.js
packages/core/src/config/projectConfig.ts
packages/core/src/linter/featureSchema.ts

Featurevisor lets you define rules in features against individual environments: https://featurevisor.com/docs/features/#rules
Currently, there's no strict requirement to have a catch-all rule (matching everyone) as the last rule inside individual environments:
```yml
environments:
production:
- key: nl
segments: netherlands
percentage: 100
- key: everyone
segments: "*" # catch-all
percentage: 0
```
A new project configuration has been introduced:
```js
// featurevisor.config.js
module.exports = {
// ...
enforceCatchAllRule: true, // false by default
};
```
If set to `true`, linting will fail if there are any features found that do not have a catch-all rule in any environment:
```
$ npx featurevisor lint
```

feat: enforce catch-all rule in features with configuration

---

packages/core/src/info/index.ts

`$ npx featurevisor info` will now also show total variables count.
Example:
```
$ npx featurevisor info
Project info:
- Revision:          28
- Total attributes:  7
- Total segments:    11
- Total features:    14
- Total variables:   13
- Total groups:      1
- Total test specs:  14
- Total assertions:  72
```

feat: show variables count from CLI

---

docs/cli.md
packages/cli/src/index.ts
packages/core/src/find-usage/index.ts

We already had these commands:
```
$ npx featurevisor find-usage --segment=my_segment
$ npx featurevisor find-usage --attribute=my_attribute
$ npx featurevisor find-usage --unusedSegments
$ npx featurevisor find-usage --unusedAttributes
```
Now, each of them can optionally receive `--authors` to show who worked on the affected entities:
```
$ npx featurevisor find-usage --segment=my_segment --authors
$ npx featurevisor find-usage --attribute=my_attribute --authors
$ npx featurevisor find-usage --unusedSegments --authors
$ npx featurevisor find-usage --unusedAttributes --authors
```
Docs: https://featurevisor.com/docs/cli/#find-usage

feat: allow showing authors when finding unused entities

---

docs/building-datafiles.md
packages/core/src/builder/buildProject.ts

Datafiles can now optionally be built without making any changes to state files (as found in `.featurevisor` directory).
```
$ npx featurevisor build --no-state-files
```
This is handy for local debugging and testing.

feat: allow building datafiles without making changes to state files

---

packages/cli/src/index.ts
packages/core/src/linter/featureSchema.ts
packages/core/src/linter/lintProject.ts
packages/core/src/linter/printError.ts
packages/core/src/tester/cliFormat.ts

Closes https://github.com/featurevisor/featurevisor/issues/230
Before, linting was not checking if a variable's value is following it's own specific type: https://featurevisor.com/docs/linting/
Now it's doing that wherever a variable value is used.
Lint variable values against their own individual defined types in:

fix: improve linting variable values

---

Makefile
docs/sdks/nodejs.md
packages/sdk/package.json
packages/sdk/webpack.config.js
packages/vue/jest.config.js
tools/getWebpackConfig.js
tsconfig.esm.json

Continuing from https://github.com/featurevisor/featurevisor/pull/322
Next to existing CommonJS build, a new ESM build is also produced with Webpack.
This should ideally fix the issues experienced in:
- https://github.com/featurevisor/featurevisor/pull/321
- https://github.com/featurevisor/featurevisor/issues/312
- https://github.com/featurevisor/featurevisor/issues/269
cc @meirroth

fix: ESM bundle for SDK

---

packages/core/json-schema/feature.json
packages/core/json-schema/segment.json

This PR resolves issues with JSON schema definitions so that they are compatible with all existing examples.
* Fixed broken reference to `plain_condition`
* Made `defaultVariation` and `variations` optional for features
* etc.
Here are the contents of the `.vscode/settings.json` configuration that helped to enable the intellisense and catch the errors. 
I also have 
I considered adding this into the project so it becomes a first-class concern as new features are being developed, but I'll leave it up to @fahad19 to decide if it belongs in this repo or only in user-land!
Thanks for working on this library!
```json
{
"yaml.schemas": {
"packages/core/json-schema/feature.json": "/features/*",
"packages/core/json-schema/segment.json": "/segments/*",
"packages/core/json-schema/attribute.json": …
```

chore: update json schemas to match examples

---

examples/example-1/attributes/continent.yml
examples/example-1/segments/eu.yml
examples/example-1/tests/eu.spec.yml
packages/sdk/src/conditions.ts

- we may use `notIn` operator in conditions inside a segment against an attribute
- but we may not ALWAYS pass that attribute in context when evaluating values with SDKs
- in those cases, notIn should still match because the value in context is not any of the strings in provided list in segment
- test spec added by creating a new `eu` segment
- it will match if `continent = 'europe' AND country != 'gb'`
- it should still match if `content = 'europe'` AND `country` is never passed in the context
When dealing with `array` values in conditions (applies to `in` and `notIn` operators only), we had an extra check in SDK to see if the corresponding attribute's value is of type `string` in the given context.
Which made sense because we are only expecting to deal with an array of strings.
But …

fix: non-existent property in context when checking in and noIn conditions

---

LICENSE
examples/example-1/tests/eu.spec.yml
packages/sdk/src/conditions.ts

Continuation of the fix from https://github.com/featurevisor/featurevisor/pull/328

fix: in operator with non-existent context value

---

docs/building-datafiles.md
docs/cli.md
docs/glossary.md
docs/testing.md
examples/example-1/Makefile
packages/core/src/assess-distribution/index.ts
packages/core/src/benchmark/index.ts
packages/core/src/builder/buildDatafile.ts
packages/core/src/builder/buildProject.ts
packages/core/src/cli/cli.ts
packages/core/src/config/projectConfig.ts
packages/core/src/evaluate/index.ts
packages/core/src/tester/testProject.ts
packages/sdk/src/datafileReader.ts
packages/types/src/index.ts

**TL;DR**: more optimized datafiles, with initial benchmarks suggesting **~29x faster** evaluations by SDK.
If the numbers are good, merge.
Tested against `examples/example-1` project running the evaluation **1 million** times:
```
$ npx featurevisor benchmark --environment=production --feature=discount --context='{"country": "nl", "userId": "123"}' --n=1000000 --schema-version=1 --inflate=76
Running benchmark for feature "discount"...
Building datafile containing all features for "production"...
Datafile build duration: 17ms
Datafile size: 528.10 kB
Features count: 1001
Segments count: 539
Attributes count: 385
...SDK initialized
Against context: {"country":"nl","userId":"123"}
Evaluating flag 1000000 times...
Evaluated value : false
Total duration  : 12s 100ms
Average duration: 0.0121ms …
```

feat: datafile schema v2

---

docs/building-datafiles.md
docs/configuration.md
packages/core/src/builder/buildProject.ts
packages/core/src/datasource/adapter.ts
packages/core/src/datasource/filesystemAdapter.ts

A new option introduced in CLI, that allows overriding the project configuration for the directory path where new generated datafiles will be written under:
```
$ npx featurevisor build --datafiles-dir=./custom-datafiles-dir
```
Be default it will still write datafiles to `dist` directory, which is configurable via the `outputDirectoryPath` option in `featurevisor.config.js` file: https://featurevisor.com/docs/configuration/

feat: pass custom datafiles directory path from CLI

---

packages/cli/package.json
packages/core/package.json
packages/sdk/package.json
packages/sdk/src/datafileReader.spec.ts
packages/sdk/src/datafileReader.ts

- SDK evaluations were made faster recently with a new v2 datafile schema: https://github.com/featurevisor/featurevisor/pull/334
- It still required users to build datafiles with `$ npx featurevisor build --schema-version=2`
Even if fetched datafile is of schema v1, SDK will now internally convert it to v2 equivalent data structure in the runtime so it can benefit from O(1) level lookups instead of O(n).
Every time the datafile content it set to the SDK, it will do the conversion once. And for any subsequent evaluations, it will benefit from faster lookups.
Just upgrade to latest `@featurevisor/sdk` package, nothing else is needed to be done by consumers.

fix: convert to datafile schema v2 internally

---

.github/workflows/publish.yml
packages/types/README.md

Published packages will have dependencies marked with exact versions, without any punctuations like `^` in the beginning of the dependency version numbers.
This will make it easier to downgrade to lower versions in case people have issues with more recent versions.

chore: publish packages with exact versions

---

examples/example-1/features/showNotification.yml
examples/example-1/tests/showNotification.spec.yml
packages/sdk/src/feature.ts

When the feature's matched rule has a percentage of `0`, it should be always disabled without making it go through bucketing process.
See `example-1` project's `showNotification` feature (along with its test spec) introduced in the diff.
Every feature defines how they wish to be bucketed against users/devices (or any other attribute) via `bucketBy` property: https://featurevisor.com/docs/features/#bucketing
Learn more about bucketing logic here: https://featurevisor.com/docs/bucketing/
During evaluation, a bucket value is generated consistently for the same user/device against the same feature, which ranges between 0 and 100,000 (it's actually 0 and 100, but the integer value is multiplied by 1000 to account for 3 decimal places).
Learn more about how to assess distribution via CLI here …

fix: matched rules with percentage of 0 should be disabled

---

docs/configuration.md
packages/core/src/config/projectConfig.ts
packages/core/src/linter/featureSchema.ts

Introduced new (optional) configuration params in `featurevisor.config.js`:
```
// featurevisor.config.js
module.exports = {
// ...
// new configs
maxVariableStringLength: 28,
maxVariableArrayStringifiedLength: 41,
maxVariableObjectStringifiedLength: 124,
maxVariableJSONStringifiedLength: 16,
};
```
If they are available as configs, linting will pick up issues if any:
```
$ npx featurevisor lint
```

feat: allow setting max character limits for variables

---

examples/example-1/features/sidebar.yml
packages/core/src/builder/buildDatafile.ts
packages/core/src/evaluate/index.ts
packages/sdk/src/datafileReader.ts
packages/sdk/src/evaluate.ts
packages/types/src/index.ts

Feature definitions have `variablesSchema` which is an array: https://featurevisor.com/docs/features/#variables
When evaluating variables, this schema is looked up by the SDK, which results into an O(n) lookup.
Without breaking the API, those who wish to benefit from v2 datafile schema, can build their datafiles doing:
```
$ npx featurevisor build --schema-version=2
```
As well as for testing for improved confidence:
```
$ npx featurevisor test --schema-version=2
```
And the generated datafile will contain `variablesSchema` of the features as a dictionary (object) resulting into O(1) lookups.
Irrespective of generating datafiles in v2 format, the SDK will still optimize the data structure of v1 datafiles when parsing datafile internally resulting into O(1) lookups.
Because of faster …

feat: variables schema as dictionary

---

docs/features.md
examples/example-1/features/newRedesign.yml
packages/core/json-schema/feature.json
packages/core/src/builder/buildDatafile.ts
packages/core/src/linter/featureSchema.ts
packages/sdk/src/evaluate.ts
packages/types/src/index.ts

We could always deprecate features before, so that warnings would appear when SDK would evaluate the feature:
```yml
deprecated: true
```
Now, we can also deprecate variables inside a feature to emit similar warnings:
```yml
variablesSchema:
- key: foo
type: string
defaultValue: hello world
deprecated: true # new property here
```

feat: allow deprecating variables

---

packages/site/src/components/HistoryTimeline.tsx
packages/site/src/components/ListAttributes.tsx
packages/site/src/components/ListFeatures.tsx
packages/site/src/components/ListSegments.tsx
packages/site/src/components/ShowAttribute.tsx
packages/site/src/components/ShowFeature.tsx
packages/site/src/components/ShowSegment.tsx

Encode entity key names in URLs, to avoid issues with namespaced keys.
Refs https://github.com/featurevisor/featurevisor/pull/346

fix: namespaces in generated site

---

docs/cli.md
examples/example-1/features/foo.yml
packages/core/src/cli/plugins.ts
packages/core/src/index.ts
packages/core/src/list/index.ts
packages/core/src/tester/index.ts
packages/types/src/index.ts

Allow listing and filtering entities (features, segments, attributes) via CLI.
See diff for docs.

feat: list entities from CLI

---

examples/example-1/tests/features/qux.spec.yml
packages/sdk/src/evaluate.ts

- A feature with variables and variations, where
- each variation has its own set of variable overrides, and
- the variation itself is overridden at rule level, then
- variable evaluation was not taking the overridden variation from rule into account
- Extra check added at variation evaluation level to also check for variation that is overridden at rule level
- `example-1` project's test specs updated accordingly

fix: variable evaluation when variation is overridden from rule

---

packages/core/src/builder/traffic.ts
packages/sdk/src/feature.ts
packages/types/src/index.ts

- `feature.traffic[].allocation` is used for allocating variations (`Traffic.allocation` type)
- When the feature has no variations, it will always be an empty array in datafiles
- This causes unnecessary additional lines in datafile for simple features with no variations, that we can avoid
In v2, we can remove this property if an empty array, resulting in smaller datafiles. See #326.
To avoid any breaking changes now, we are making 1.x SDK support it when `Traffic.allocation` is not present.
This will make migrating from latest 1.x to 2.0 later with ease.

chore: allow empty allocation for features without variations
